Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 355, in parameter_run
    energies[(param.alpha, param.beta)]
KeyError: (0.02, 0.22)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: 'Barotropic/Meshes/Box_Shp/box_shape_(-0.050481877734615224,0.0)x(0.050481877734615224,0.10096375546923045).shp' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fiona/ogrext.pyx", line 1028, in fiona.ogrext.WritingSession.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: 'Barotropic/Meshes/Box_Shp/box_shape_(-0.050481877734615224,0.0)x(0.050481877734615224,0.10096375546923045).shp' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fiona/_shim.pyx", line 110, in fiona._shim.gdal_create
  File "fiona/_err.pyx", line 291, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_AppDefinedError: Barotropic/Meshes/Box_Shp/box_shape_(-0.050481877734615224,0.0)x(0.050481877734615224,0.10096375546923045).shp is not a directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 463, in <module>
    parameter_run(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 358, in parameter_run
    barotropic_solution, baroclinic_solution = startup(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 112, in startup
    barotropic_mesh = make_canyon_meshes.mesh_generator(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/make_canyon_meshes.py", line 106, in mesh_generator
    P, T = uniform_box_mesh.main(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/uniform_box_mesh.py", line 97, in main
    create_shoreline_geometry(x0, xN, y0 - eps, y0, name=fname)
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/uniform_box_mesh.py", line 20, in create_shoreline_geometry
    gpd.GeoDataFrame(
  File "/home/home02/ml14je/.conda/envs/oceanmesh2/lib/python3.9/site-packages/geopandas/geodataframe.py", line 1114, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/home02/ml14je/.conda/envs/oceanmesh2/lib/python3.9/site-packages/geopandas/io/file.py", line 393, in _to_file
    with fiona.open(
  File "/home/home02/ml14je/.conda/envs/oceanmesh2/lib/python3.9/site-packages/fiona/env.py", line 408, in wrapper
    return f(*args, **kwargs)
  File "/home/home02/ml14je/.conda/envs/oceanmesh2/lib/python3.9/site-packages/fiona/__init__.py", line 280, in open
    c = Collection(path, mode, crs=crs, driver=driver, schema=this_schema,
  File "/home/home02/ml14je/.conda/envs/oceanmesh2/lib/python3.9/site-packages/fiona/collection.py", line 165, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 1032, in fiona.ogrext.WritingSession.start
  File "fiona/ogrext.pyx", line 1033, in fiona.ogrext.WritingSession.start
  File "fiona/_shim.pyx", line 114, in fiona._shim.gdal_create
fiona.errors.DriverError: Barotropic/Meshes/Box_Shp/box_shape_(-0.050481877734615224,0.0)x(0.050481877734615224,0.10096375546923045).shp is not a directory.
