Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 355, in parameter_run
    energies[(param.alpha, param.beta)]
KeyError: (0.02, 0.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 463, in <module>
    parameter_run(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 358, in parameter_run
    barotropic_solution, baroclinic_solution = startup(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 112, in startup
    barotropic_mesh = make_canyon_meshes.mesh_generator(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/make_canyon_meshes.py", line 106, in mesh_generator
    P, T = uniform_box_mesh.main(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/uniform_box_mesh.py", line 122, in main
    shore = Shoreline(fname, extent_.bbox, h_min,
  File "/nobackup/ml14je/Packages/oceanmesh2/oceanmesh/geodata.py", line 460, in __init__
    self.shp = shp
  File "/nobackup/ml14je/Packages/oceanmesh2/oceanmesh/geodata.py", line 489, in shp
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Barotropic/Meshes/Box_Shp/box_shape_(-0.050481877734615224,0.0)x(0.050481877734615224,0.10096375546923045).shp'
