Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 355, in parameter_run
    energies[(param.alpha, param.beta)]
KeyError: (0.02, 0.06)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 463, in <module>
    parameter_run(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 358, in parameter_run
    barotropic_solution, baroclinic_solution = startup(
  File "/nobackup/ml14je/Packages/baroclinicSWEs/baroclinicSWEs/Analyses/Model B/parameter_runs.py", line 112, in startup
    barotropic_mesh = make_canyon_meshes.mesh_generator(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/make_canyon_meshes.py", line 106, in mesh_generator
    P, T = uniform_box_mesh.main(
  File "/nobackup/ml14je/Packages/barotropicSWEs/barotropicSWEs/MeshGeneration/uniform_box_mesh.py", line 122, in main
    shore = Shoreline(fname, extent_.bbox, h_min,
  File "/nobackup/ml14je/Packages/oceanmesh2/oceanmesh/geodata.py", line 469, in __init__
    polys = self._read()
  File "/nobackup/ml14je/Packages/oceanmesh2/oceanmesh/geodata.py", line 554, in _read
    s = self.transform_to(gpd.read_file(self.shp), self.crs)
  File "/nobackup/ml14je/Packages/oceanmesh2/oceanmesh/geodata.py", line 531, in transform_to
    if not gdf.crs.equals(dst_crs):
AttributeError: 'NoneType' object has no attribute 'equals'
